### ISSUE TITLE
Rejilla

### ISSUE THREAD

**Issue by gpm0009** [gpm0009/TFG_MetrominutoWeb#100]
Recolocar los nodos en un sistema ded rejilla

**Comment by gpm0009** [comment]
multiplicando el radio por 4, me los separa, por que justo coincide en segmentos diferentes.
![image.png](https://images.zenhubusercontent.com/5a001aa88a75884b90862723/ca160001-6b75-40c0-bd1a-f56e1141c17c)

Jugando un poco con ello, he puesto otra distancia para cada segmento. Imagino que segun vaya haciendo pruebas elegiré cuál lo cumple mejor.
![image.png](https://images.zenhubusercontent.com/5a001aa88a75884b90862723/6cf78fd2-9c92-4e15-901a-f4691bda388a)

**Comment by alvarag** [comment]
Queda mejor en el segundo caso, como esperábamos, pero tampoco está feo en el primero la verdad.

A ver si conseguimos ajustar bien las labels ;)
