### ISSUE TITLE
Reunión 2

### ISSUE THREAD

**Issue by alvarag** [gpm0009/TFG_MetrominutoWeb#11]
Comentarios realizados:

- Seguimiento de [PEP-8](https://www.python.org/dev/peps/pep-0008/).
- Utilizar PyCharm y solicitar la licencia de estudiante.
- Crear un ```.gitignore```.
- Guía de estilo para [JavaScript de Google](https://google.github.io/styleguide/jsguide.html).
- Plantilla de [LaTeX](https://github.com/ubutfgm/plantillaLatex)
- API para documentar en LaTeX: MikTeX (motor) y TeXstudio (editor)
-

**Comment by gpm0009** [comment]
- Posibilidad de usar [Docker](https://www.docker.com/resources/what-container) mas adelante.

**Comment by gpm0009** [comment]
Creadas issues correspondientes.
