### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by gpm0009** [gpm0009/TFG_MetrominutoWeb#110]
Investigar acerca de la release de GitHub

**Comment by gpm0009** [comment]
@alvarag Como comentamos hace tiempo de publicar versiones, ¿estaría bien publicar una ahora que ya he arreglado el orden de los rectángulos?

**Comment by alvarag** [comment]
Sí, yo creo que podría ser una buena idea. Puedes ver cómo publicar releases en la documentación de Github: https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository

Pero que no te lleve mucho tiempo, esta sería la versión 0.1 o algo así.
