### ISSUE TITLE
Botón exportar el grafo.

### ISSUE THREAD

**Issue by gpm0009** [gpm0009/TFG_MetrominutoWeb#122]
Botón para exportar el grafo y descargarlo como una imagen

**Comment by gpm0009** [comment]
@cgosorio @alvarag He estado buscando como hacer esto, y las soluciones que encuentro es pintando el svg dentro de un canvas. Después de muchos intentos he conseguido hacerlo, pero pierde bastante calidad y no guarda el tamaño.....No se si alguna vez habéis visto algo de esto o lo estoy liando mucho :/

**Comment by cgosorio** [comment]
Si he entendido bien tu problema, creo que el siguiente enlace puede ayudarte a encontrar la solución: https://stackoverflow.com/questions/38477972/javascript-save-svg-element-to-file-on-disk.

Creo que tu caso es más sencillo que el planteado en la consulta en stackoverflow porque tu no estás dando estilo al SVG a través de CSS.

**Comment by gpm0009** [comment]
@cgosorio mmm si, pero con eso lo estas descargando como un svg, no como una imagen png o jpg, que es donde viene el problema, que igual me he explicado mal perdona.

**Comment by cgosorio** [comment]
No. Si lo interesante es bajarlo como SVG, que es un formato vectorial.
Si también quieres convertirlo a PNG, sí que parece que hacerlo a través del canvas es la solución, ¿algunos de los enlaces que has encontrado es uno de estos?

- https://bl.ocks.org/mbostock/6466603
- https://github.com/exupero/saveSvgAsPng

**Comment by gpm0009** [comment]
Ah, pues pense que queríamos como png, lo entendí mal entonces perdona. Si, el primero ya lo había mirado y probado lo del canvas, pero no me funciona ninguno (en casi todos he encontrado lo mismo), lo máximo que he conseguido descargar a sido esto:
![fileName (13)](https://user-images.githubusercontent.com/33413579/84303189-d5291d00-ab56-11ea-8ceb-df70ab8ec744.png)

Lo de npm no lo había encontrado. Pruebo a ver

**Comment by cgosorio** [comment]
Creo que el problema puede estar en las dimensiones que tienes configuradas para el SVG. En el SVG no es demasiado relevante, porque al ser un formato vectorial, si es necesario hacer zoom, no se pierde nada de calidad. Pero las dimensiones sí que son relevantes cuando lo pases a un formato de mapa de bits. Mira a ver si con otras dimensiones del SVG (mucho mayores) la calidad de la exportación a PNG es más decente.

**Comment by gpm0009** [comment]
Vale, voy a probar a ver. Muchas gracias!
