### ISSUE TITLE
Google Auth

### ISSUE THREAD

**Issue by gpm0009** [gpm0009/TFG_MetrominutoWeb#124]
Incluir login con Google.

**Comment by gpm0009** [comment]
Login con [Firebase](https://cloud.google.com/appengine/docs/standard/python/authenticating-users-firebase-appengine?hl=es-419).

**Comment by gpm0009** [comment]
Buenas @alvarag @cgosorio , he hecho una página de inicio para el inicio de sesión y demas y tengo un par de dudas (así mañana puedo enseñaros todo junto). 

![image.png](https://images.zenhubusercontent.com/5a001aa88a75884b90862723/ba243c8d-515c-4d5b-b27d-07e884586311)

Al hacer login, debería redirigir al usuario a el mapa? o estaría mejor incluir otro recuadro como el de 
Repositorio con una breve explicación (modo lista) de lo que puede hacer en el mapa?  Y una vez esté logueado habilitar un botón para que pueda acceder?

No se si me he explicado ^^.

**Comment by gpm0009** [comment]
PD: cuando el usuario está logueado aparece su correo en vez del botón de iniciar sesión.

![image.png](https://images.zenhubusercontent.com/5a001aa88a75884b90862723/3c0499c6-f2f0-43de-b922-9c7257e8e2ec)

**Comment by alvarag** [comment]
Creo que me lo tendrás que explicar en la reunión que no me está quedando claro.

Yo creo que algo fácil/intuitivo sería:
- Pantala de Login
- Accede
- Pantalla inicial con el mapa para seleccionar puntos.
- En cualquier momento si pulsa sobre su mail que aparezca "Salir"

**Comment by gpm0009** [comment]
Vale, a eso me refería, que cuando hace login pasa directamente a ver el mapa.
