### ISSUE TITLE
Pruebas con la API

### ISSUE THREAD

**Issue by gpm0009** [gpm0009/TFG_MetrominutoWeb#126]
Empezar las pruebas con la API de google

**Comment by gpm0009** [comment]
@cgosorio @alvarag Buenas, por confirmar:
supongamos que los puntos selecionados son:
- Plaza Mío Cid, 2, 09004 Burgos, Spain
- Plaza Rey San Fernando, 9, 09003 Burgos, Spain
- Calle San Esteban, 24, 09003 Burgos, Spain
- Calle Francisco Salinas, 2, 09003 Burgos, Spain
- Calle Dr. José Luis Santamaría, 6, 09001 Burgos, Spain
- Av. Reyes Católicos, 138, 09004 Burgos, Spain
- Plaza de Sta. Teresa, 4, 09002 Burgos, Spain
- Calle Sta. Clara, 53, 09002 Burgos, Spain

En la lista que aparece junto al mapa, las direcciones serían:
- Plaza Mío Cid, 2
- Plaza Rey San Fernando, 9
- Calle San Esteban, 24
- Calle Francisco Salinas, 2
- Calle Dr. José Luis Santamaría, 6
- Av. Reyes Católicos, 138
- Plaza de Sta. Teresa, 4
- Calle Sta. Clara, 53

Y luego, en el svg, lo mismo pero sin el número?

**Comment by cgosorio** [comment]
En el SVG también podrían aparecer con el número. Ya no recuerdo que habíamos hablado respecto a esto, pero no poniendo el número tampoco nos ahorramos tanto.

**Comment by alvarag** [comment]
Como veas, igual puede confundir el número con los minutos en algún caso de _apelotonamiento_. Así que igual mejor sin número en el SVG como decías
