### ISSUE TITLE
Cambiar página de inicio

### ISSUE THREAD

**Issue by gpm0009** [gpm0009/TFG_MetrominutoWeb#129]
Añadir logos de la universidad, mensaje iniciar sesión y cambiar el orden.

1. UBU
2. Titulo: Metrominuto Web.
3. Logos aplicaciones.

**Comment by gpm0009** [comment]
Me queda el logo de la EPS y el de Informática, que no consigo encontrarlos en png y pues por preguntar........ :/ no los tendréis por un casual no @alvarag @cgosorio ???

![image.png](https://images.zenhubusercontent.com/5a001aa88a75884b90862723/cd18d279-9f00-40bc-a31b-88583e2a1486)

**Comment by cgosorio** [comment]
Si puedes usar `svg`, mejor que `png`. Te los paso en ambos formatos.


[Archivo comprimido.zip](https://github.com/gpm0009/TFG_MetrominutoWeb/files/4840199/Archivo.comprimido.zip)

**Comment by gpm0009** [comment]
Ooh, genial, Muchas gracias!

**Comment by gpm0009** [comment]
![image.png](https://images.zenhubusercontent.com/5a001aa88a75884b90862723/03f5b827-adb8-4a81-a424-23efc45eded9)

**Comment by cgosorio** [comment]
Igual podrías añadir también el logo de LaTeX.

https://es.m.wikipedia.org/wiki/Archivo:LaTeX_logo.png
