### ISSUE TITLE
Distancia entre ciudades

### ISSUE THREAD

**Issue by gpm0009** [gpm0009/TFG_MetrominutoWeb#133]
He comprobado esto, y resulta que.....Funciona @cgosorio @alvarag !!!!! Sale marcador por que es una prueba que e hecho sin el .split()
![image.png](https://images.zenhubusercontent.com/5a001aa88a75884b90862723/42fc3072-dcb2-4404-8b50-7322f8a4d746)

![image.png](https://images.zenhubusercontent.com/5a001aa88a75884b90862723/cbe7be30-342d-4235-b18c-a0fd4723ff18)

**Comment by cgosorio** [comment]
Estupendo, tenía la sospecha de que debería funcionar, pero está bien tener la constatación experimental.

**Comment by alvarag** [comment]
Está bien saberlo por si te preguntan los miembros del tribunal
