### ISSUE TITLE
Enviar datos al servidor

### ISSUE THREAD

**Issue by gpm0009** [gpm0009/TFG_MetrominutoWeb#28]
Duda:
tengo dos opciones para enviar los marcadores al servidor y no se cual puede ser mejor. Me decantaría por la segunda. De todos modos:
- Opcion 1 -> crear una lista auxiliar para pasar los elementos
$("#saveButton").click(function () {
            //alert(markers[0].label);
            var list = []
            for(i=0;i<markers.length;i++){
                list.push(markers[i].position);
            }
            $.ajax({
                type: "POST",
                contentType: "application/json;charset=utf-8",
                {#url: "/getMarks",#}
                traditional: "true",
                data: JSON.stringify(list),
                dataType: "json"
            });
        });

- Opcion 2 --> Hacer una peticion post por cada elemento
$("#saveButton").click(function () {
            //alert(markers[0].label);
            var list = []
            for(i=0;i<markers.length;i++){
                var marcador = {'position' : markers[i].position,
                                'label' : markers[i].label};
                console.log(marcador);
                $.ajax({
                type: "POST",
                contentType: "application/json;charset=utf-8",
                {#url: "/getMarks",#}
                traditional: "true",
                data: JSON.stringify(marcador),
                dataType: "json"
            });
            }
        });

**Comment by cgosorio** [comment]
En general las solicitudes al servidos es mejor minimizarlas, con lo que de las dos opciones que propones, la primera sería mejor.

En cuanto el enlace que has elegido para recibir los marcadores «getMarks» igual no es el mejor nombre, dado que ese enlace no se está usando para obtener marcas, sino para enviarlas, sería mejor «setMarks», «registerMarks» o «pushMarks».
