### ISSUE TITLE
Crear archivo .json

### ISSUE THREAD

**Issue by gpm0009** [gpm0009/TFG_MetrominutoWeb#41]
Para usar la libreria d3 tube map, es necesario crear con nuestros datos la estructura necesaria de json para poder dibujar las líneas.
- stations
- lines
- ¿river?

**Comment by alvarag** [comment]
De momento el introducir elementos como ríos, parques, etc. lo dejamos a futuro. Sí que creo que una vez dibujado el mapa sería interesante que el usuario pudiera _pintar_ encima.

**Comment by gpm0009** [comment]
@alvarag Pudiera pintar en que sentido? dibujar trazas de "nuevas lineas" y que se calcules la distancia/tiempo (opcion tambien de eliminar puntos), o.....?

**Comment by alvarag** [comment]
Yo creo que la idea sería que el usuario pueda decidir añadir/eliminar arcos del grafo: de este modo elige a groso modo qué arcos le interesan y luego de manera manual lo define más concretamente.

Además, yo creo que estaría bien que pudiera "pintar" o "decorar" con zonas de parques o ríos... eso sería fácil y le daría mayor vistosidad a los diagramas finales.

No obstante lo vemos en la siguiente reunión

**Comment by gpm0009** [comment]
En el [ejemplo ](https://bl.ocks.org/johnwalley/9b6d8af7a209b95c5b9dff99073db420)de uso de la librería, utliza datos proporcionados por Google, o datos que podemos usar en los APIs de google, como por ejemplo el place_id.
Esto viene bien de cara a tener todos los datos necesarios en el svg que genera, ya que hace mas facil futuras llamadas (en el caso de que hagan falta).

**Comment by gpm0009** [comment]
Haciendo varias pruebas, me he dado cuenta que no es necesario especificar donde debe hacer la curva. Lo dibuja la biblioteca sola en funcion de un nodo intermedio y de las posiciones, es decir:
```
"nodes": [
        {
          "coords": [23, -4],
          "name": "StationA",
          "labelPos": "S"
        },
        {
          "coords": [31, -4]
        },
        {
          "coords": [31, 2],
          "name": "StationB",
          "marker": "interchange",
          "labelPos": "E"
        },
```
Con una estructura del estilo, con un "nodo" intermedio contenido las coordenadas del anterior, la bibloteca estable la curva donde le parece.

**Comment by gpm0009** [comment]
Se deja de usar esta biblioteca, es útil si generamos a mano el archivo JSON. No sirve para la automatización que queremos del proceso.
