### ISSUE TITLE
Reunión semanal

### ISSUE THREAD

**Issue by alvarag** [gpm0009/TFG_MetrominutoWeb#42]
Buenas tardes, ¿hemos quedado esta semana? No tengo apuntado en el calendario, pero creo que nos tocaba, ¿no?

**Comment by gpm0009** [comment]
@alvarag eso es. Yo tengo apuntado el jueves a las 19:30. Si os va mal o lo que sea me decís.

**Comment by alvarag** [comment]
Yo no me acordaba y tengo defensa de prácticas. Pero César sí que estará. Él me pondrá al día
