### ISSUE TITLE
Posponer la reunión

### ISSUE THREAD

**Issue by alvarag** [gpm0009/TFG_MetrominutoWeb#46]
Buenos días,

Con motivo de la visita de unos investigadores polacos, debemos posponer la reunión a más tarde (el miércoles) o dejarla para la próxima semana.

Saludos,

**Comment by gpm0009** [comment]
Buenas,
imagino que tendreis alguna reunión o asi, tampoco es cuestión de estar pendiente de si acabais o no (tanto por vuestra parte como por la mia), asi que lo podemos dejar para la semana que viene si preferís y así quedamos a una hora y ya. Si no por mi parte reunirnos el miercoles a las 20:00 tampoco me importa, pero ya más tarde de ahí me parece tarde.

Si tengo alguna duda os comento por aquí, pero puedo seguir haciendo cosas a parte de los objetivos iniciales de este sprint.

PD: Creo que uno de los investigadores es de la uni en la que estuve el año pasado xD

**Comment by alvarag** [comment]
Como veas, el miércoles a las 20:00 estaríamos ya libres. Así que si quieres podemos dejarla ahí.

**Comment by gpm0009** [comment]
ah vale, entonces guay. Miercoles a las 20:00 entonces
