### ISSUE TITLE
Herramientas para diagramas

### ISSUE THREAD

**Issue by alvarag** [gpm0009/TFG_MetrominutoWeb#49]
Casos de uso:

- https://plantuml.com/use-case-diagram

Secuencia:

- https://bramp.github.io/js-sequence-diagrams/

**Comment by gpm0009** [comment]
- [LucidChart](https://www.lucidchart.com): Permite licencia educativa con el usuario de la universidad. Trae plantillas, permite exportar, integrar con diferentes herramientas, etc.
