### ISSUE TITLE
Comienzo del proyecto.

### ISSUE THREAD

**Issue by gpm0009** [gpm0009/TFG_MetrominutoWeb#5]
Crear el repositorio en el ordenador, junto con la estructura de carpetas.

**Comment by alvarag** [comment]
Yo le cambiaría el nombre a: TFG-Metrominuto o algo similar, para que sea más descriptivo

**Comment by alvarag** [comment]
Por cierto, en la próxima reunión recuérdanos el tema de la documentación: para ir empezando a la par con ella.

**Comment by gpm0009** [comment]
Perfecto, me lo apunto.
