### ISSUE TITLE
Documentación Sprint 9

### ISSUE THREAD

**Issue by gpm0009** [gpm0009/TFG_MetrominutoWeb#50]
Actualizar documentación Sprint 9:
- Planificacion temporal.
- Manual del programador.
- Documentar por qué se deja de usar tube map
- Documenrtar conf inicial de tube map.

**Comment by alvarag** [comment]
Comentarios sobre memoria y anexos.

[anexosAAG.pdf](https://github.com/gpm0009/TFG_MetrominutoWeb/files/4256629/anexosAAG.pdf)
[memoriaAAG.pdf](https://github.com/gpm0009/TFG_MetrominutoWeb/files/4256631/memoriaAAG.pdf)
