### ISSUE TITLE
Layouts para el dibujado de grafos

### ISSUE THREAD

**Issue by alvarag** [gpm0009/TFG_MetrominutoWeb#52]
Como hemos hablado, lo _ideal_ sería un layout que conservase cierta topología pero reescalase.

La tesis que habla de ello: https://pdfs.semanticscholar.org/d2f5/1f09bfe73b1f66d9e36da33041cbb68ac1cc.pdf

**Comment by alvarag** [comment]
Volviendo al tema de evitar que lugares alejados nos distorsionen el gráfico, vuelvo a la opción de utilizar el logaritmo:

![imagen](https://user-images.githubusercontent.com/9881614/81044179-1bce8c00-8eb4-11ea-8340-5f7ea090010a.png)

Como ves en las distancias hay mucha variación (min 8 y max 180). En cambio, cuando haces el logaritmo de la distancia (la multiplicación por 10 era para aumentar un poco): en este caso la variabilidad es muy baja, min 9 y máx 22.

Es una operación muy simple, por lo que debería funcionarte.

**Comment by gpm0009** [comment]
Vale, lo implemento. Quizás cuando lo intenté no vi que funcionase por que el ejemplo no era el adecuado ahora que le doy otra vuelta y para el jueves lo tengo.
