### ISSUE TITLE
Reunión

### ISSUE THREAD

**Issue by gpm0009** [gpm0009/TFG_MetrominutoWeb#55]
Mañana no voy a poder asistir a la reunión, sería posible hacerla el jueves? De las 12:30 en adelante podría pasarme por la universidad a cualquier hora.
Perdón por las molestias.

**Comment by alvarag** [comment]
Por mi parte no habría problema, se lo comento a César y te confirmamos

**Comment by alvarag** [comment]
Quedamos mañana a las 12:30

**Comment by gpm0009** [comment]
Genial, gracias!
