### ISSUE TITLE
Reunion Sprint 12

### ISSUE THREAD

**Issue by gpm0009** [gpm0009/TFG_MetrominutoWeb#68]
Buenas,
Visto lo visto, como hacemos la reunión esta semana? por teams y os comparto pantalla? :)

**Comment by alvarag** [comment]
Sí, creo que por Teams es lo más acertado. Puedes crear un evento/reunión en el Calendar de Office365 y ahí le dices que va a ser por Teams: nos llega invitación y pista

**Comment by gpm0009** [comment]
Perfecto. Jueves misma hora (12:30)? O teneis algun inconvenente? yo siendo a partir de las 12 no tengo problema ninguno.

**Comment by alvarag** [comment]
No creo que César tenga compromisos, no obstante le pregunto. De momento, si no te decimos nada, es el jueves a las 12:30.
Te encargas tu de crear la reunión, ¿ok?

**Comment by gpm0009** [comment]
Perfecto
