### ISSUE TITLE
Problema con la normalización

### ISSUE THREAD

**Issue by gpm0009** [gpm0009/TFG_MetrominutoWeb#69]
Tengo un problema al normalizar los puntos para escalarlo en el SVG, no se si mañana tendríais 5 mins para mirarlo, que es probable que sea una cosa de nada y me estoy volviendo loco.
Basicamente consiste en que despues de normalizar las coordenadas tengo que rotar la imagen para que los puntos se asemejen a las coordenadas reales.

**Comment by gpm0009** [comment]
- Puntos:
![image](https://user-images.githubusercontent.com/33413579/77339766-92606180-6d2c-11ea-8f44-d4d864559e73.png)

- sin rotar:
![image](https://user-images.githubusercontent.com/33413579/77339819-aa37e580-6d2c-11ea-8d40-32f98e78e645.png)
- rotada:
![image](https://user-images.githubusercontent.com/33413579/77339948-dd7a7480-6d2c-11ea-89ac-43ac3a37727f.png)

**Comment by alvarag** [comment]
¿Y qué problema hay con el rotado? No veo muy bien cómo puedo ayudar pero podemos hablar por Skype si quieres en cualquier momento, por Skype o por Teams: tengo ambos abiertos
