### ISSUE TITLE
Cambio nombre milestones

### ISSUE THREAD

**Issue by alvarag** [gpm0009/TFG_MetrominutoWeb#7]
Los milestones sería mejor que se llamase "Sprint 1", "Sprint 2"... ya que el Sprint conlleva al menos dos reuniones: la inicial y la de retrospectiva al final.

**Comment by gpm0009** [comment]
Perfecto, lo cambio ahora.

**Comment by gpm0009** [comment]
He cambiado también la descripción, que igual queda mas ordenado así.
