### ISSUE TITLE
Documentación Sprint 13

### ISSUE THREAD

**Issue by gpm0009** [gpm0009/TFG_MetrominutoWeb#71]
- Documentación latex.
- Documentar código.
- Incluir herramienta lucid charts.

**Comment by alvarag** [comment]
Comentarios sobre memoria y anexos

[memoriaAAG.pdf](https://github.com/gpm0009/TFG_MetrominutoWeb/files/4468621/memoriaAAG.pdf)

[anexosAAG.pdf](https://github.com/gpm0009/TFG_MetrominutoWeb/files/4468618/anexosAAG.pdf)
