### ISSUE TITLE
Dudas sobre Vue

### ISSUE THREAD

**Issue by gpm0009** [gpm0009/TFG_MetrominutoWeb#75]
Buenas, he estado este fin de semana intentando implementar la parte de Vue.js en el proyecto, pero a la hora de utilizarlo tengo un par de dudas. Si es posible antes de la reunión semanal del sprint, si teneis un ratillo, podríamos hablarlo y asi puedo terminar de implementarlo. Si andais muy liados tiro por otro lado y ya lo veremos.

**Comment by alvarag** [comment]
Si quieres podemos hacer una reunión, aunque me temo que poco podré ayudarte con Vue: nunca lo he usado

**Comment by cgosorio** [comment]
Yo, dependiendo de la naturaleza de la duda, igual sí que te puedo ayudar con Vue.

**Comment by gpm0009** [comment]
Básicamente cómo utilizarlo, porque no se si tengo que cambiar varias redirecciones o no. He implementao el cliente. Podría de decirse que es del estilo a Ionic(sería toda la parte de frontend utilizando una api que sería flask) y en el paso final no me queda muy claro como usarlo.
Si os va bien me parece perfecto hacer una reunión (a partir de las 12 cuando podáis vosotros) y os explico si eso que dudo que me haya explicado bien arriba.

**Comment by cgosorio** [comment]
Yo preferiría no quedar antes de las 13:00.

**Comment by gpm0009** [comment]
Ah sisi, cuando os venga bien. Yo no tengo incoveniente. Gracias.
