### ISSUE TITLE
Problema al reestructurar la app

### ISSUE THREAD

**Issue by gpm0009** [gpm0009/TFG_MetrominutoWeb#81]
Al reestructurar la app, añadiendo blueprint o añadiendo un nuevo directorio con la lógica de la app, dejando fuera la inicialización de la app, no reconoce el directorio <<static>> mientras que el directorio <<templates>> si.

![image](https://user-images.githubusercontent.com/33413579/79050938-972e7c00-7c2d-11ea-98f7-8219b33c9e1c.png)
Esto me da el error <<FileNotFoundError: [Errno 2] No such file or directory: 'static/marcadores.json'>> y no termino muy bien de entender, he probado variando la ruta (./static...), inicializando la variable de static_folder al crear la instancia de la app....

**Comment by alvarag** [comment]
Creo que tendrá que echarte una mano con esto @cgosorio , pues yo no termino de entender el problema... :S

**Comment by cgosorio** [comment]
Así, sólo con la captura es difícil saber cuál puede ser el problema. Prueba a importar el modulo `os`:
```
import os
```

Y a imprimir en tu función el directorio de trabajo:
```
print(os.getcwd())
```
Eso te puede dar una pista de cuál es el problema.

**Comment by gpm0009** [comment]
vale, muy cierto eso y de gran ayuda. Creo que ya lo probe con ese directorio y basta preguntar para que funcione. Gracias a ambos :D

**Comment by cgosorio** [comment]
¿qué quieres decir con «probe (sic) con ese **directorio**»? No te entiendo. Lo que hace `os.getcwd()` es mostrar cuál es el directorio de trabajo, eso te puede dar la pista de por que no puedes abrir el archivo usando `open('static/marcadores.json')` quizás crees que son esa ruta relativa es suficiente, pero tienes que asegurarte que la ruta es relativa con respecto al directorio correcto.
