### ISSUE TITLE
`pip install -r requirements` da error

### ISSUE THREAD

**Issue by cgosorio** [gpm0009/TFG_MetrominutoWeb#82]
Estaba intentando generar el entorno de trabajo para ver si te podía resolver la duda del directorio que no encuentra (https://github.com/gpm0009/TFG_MetrominutoWeb/issues/81), pero me ha dado este error:
```
ERROR: Could not find a version that satisfies the requirement apt-clone==0.2.1 (from -r requirements.txt (line 5)) (from versions: none)
ERROR: No matching distribution found for apt-clone==0.2.1 (from -r requirements.txt (line 5))
```
Deberías investigarlo para que cuando los miembros del tribunal trasteen con tu código, pueda recrear el entorno de trabajo sin problemas.

**Comment by gpm0009** [comment]
lo miro a ver porque teóricamente ese fichero lo genera automáticamente con: 
`pip freeze > requirements.txt`

Creo que me lo comentó @alvarag que también le puso pegas. Lo miro.

PD: en cuanto a lo del directorio ya lo he solucionado, y voy a cambiar algo la estructura de directorios del proyecto.

**Comment by gpm0009** [comment]
Vale, añade todo lo que hay en el editor, aunque no este usandolo en este proyecto. Lo miro y elimino los que no hagan falta.

**Comment by cgosorio** [comment]
Deberías documentar también en el README.md los pasos para crear el entorno python e instalar las dependencias (incluso como clonar el repositorio git). Yo el entorno lo he creado con `conda create -n metrominuto python=3.8`, pero tras activarlo con `conda activate metrominuto` el `pip install -r requierements.txt` me ha explotado con ese error.

**Comment by cgosorio** [comment]
> PD: en cuanto a lo del directorio ya lo he solucionado, y voy a cambiar algo la estructura de directorios del proyecto.

Estupendo!

**Comment by gpm0009** [comment]
Vale, me lo apunto, y corrijo el fichero también.

**Comment by gpm0009** [comment]
WTForms~=2.1
networkx~=2.4
numpy~=1.18.0
matplotlib~=3.0.3
Flask~=1.0.2
googlemaps~=4.2.0
svgwrite~=1.3.1

**Comment by cgosorio** [comment]
En el nuevo `requirement.txt`, al menos todavía son necesarias las siguientes dependencias:
```
flask_bootstrap
flask_cors
```

**Comment by gpm0009** [comment]
flask_cors la he eliminado por que no la usaba. La añdí para la comunicación con el cliente Vue.js, pero ya no hace falta.
Ya he actualizado el fichero `requirements.txt`. He hecho dos pruebas creando un nuevo entorno virtual, en Visual Studio Code y Pycharm y me ha funcionado sin problema.
