### ISSUE TITLE
Reunión Sprint 15

### ISSUE THREAD

**Issue by gpm0009** [gpm0009/TFG_MetrominutoWeb#90]
Buenas, me acabo de dar cuenta que el jueves es fiesta. Como hacemos la reunión? A mi me es indiferente el día la verdad. Lo que me digais

**Comment by alvarag** [comment]
¡Bien visto! Por mi parte podemos adelantarla al miércoles, mañana le pregutno a César

**Comment by cgosorio** [comment]
Por mí, el miércoles bien.

**Comment by gpm0009** [comment]
Perfecto
