### ISSUE TITLE
Colocación de los labels

### ISSUE THREAD

**Issue by cgosorio** [gpm0009/TFG_MetrominutoWeb#91]
Guillermo te contesto tu duda aquí mejor para que quede documentado y fácilmente localizable.

> Buenas,
> 
> se que me vas a decir que me lo explicaste el otro día, y lo apunté y creí
> haberlo entendio, pero soy incapaz de sacarlo.  Para el calculo de dónde poner
> los label de los tiempos dijimos de dibujarlos en la recta perpendicular por el
> punto medio. Llego a sacar el punto medio y el vector perpendicular unitario.
> Luego... me pierdo 😕 y creo que será algo que no veo....
> 
> Gracias de antemano.
> 
> Un saludo,
> 
>  Guille

Si tienes el punto medio xm, ym y el vector unitario perpendicular xv, yv, lo único que tienes que hacer es sumar un porcentaje del vector a las coordenadas. Experimenta con el valor. Digamos que es ε, la coordenada de referencia será ahora los puntos (xm+εxv, ym+εyv) y (xm-εxv, ym-εyv) están cada uno a un lado del punto medio.

En realidad, todavía hay un paso de dificultad. Necesitas determinar 8 coordenadas en torno al texto que quieres ubicar, las cuatro esquinas y los cuatro puntos medios del rectángulo que constituye el texto de la etiqueta. La coordenada inferior izquierda (x, y)  es fácil de conseguir, dado que coincide con la de los atributos del elemento text de svg. Las otras son un poco más complicadas, dado que depende de atributos como el tamaño de fuente o la fuente específica que se esté utilizando. Luego te pego unos enlaces para esto. Ahora vamos a suponer que las longitudes son lx y ly. Las coordenadas de las «anclas» (voy a llamar así a cada uno de los 8 puntos), serían: (x, y), (x+lx/2, y), (x+lx, y), (x+lx, y+ly/2), (x+lx, y+ly), (x+lx/2, y+ly), (x, y+ly), (x, y+ly/2). Tendrías que simular el colocar cada una de esas coordenadas en las dos posiciones a ambos lados de la línea, para comprobar para cuál no se producen solapamientos.

Ahora para determinar las dimensiones del rectángulo de texto, algunos enlaces, son para hacerlo desde Python, pero si eso no funciona, también podrías utilizar «el truco» de generar una página de prueba en el servidor y usar javascript para obtener la dimensión  (de hecho en uno de los enlaces se explica un truco parecido que implica renderizar el svg como imagen y obtener el tamaño de la imagen):

- https://stackoverflow.com/questions/6723669/get-svg-text-size-in-python
- https://stackoverflow.com/questions/24337531/how-to-determine-text-width-and-height-when-using-svgwrite-for-python/48387748
- https://stackoverflow.com/questions/1636842/svg-get-text-element-width

Lo de las 8 anclas, sería para hacerlo de forma sistemática considerando todas las opciones, pero también podrías jugar con el atributo `text-anchor` de svg, aunque creo que eso igual lo hace todo más complicado: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-anchor.

Respecto a lo de detectar el solapamiento de elementos, podría usar alguno de los algoritmos existentes para detectar la colisión de rectángulos (las líneas las podrías considerar como pequeños rectángulos). Aquí algunos enlaces:

- https://helmetwarsgame.wordpress.com/2011/12/01/funcion-de-deteccion-de-colision-entre-dos-rectangulos-de-un-plano/
- https://alfffa.wordpress.com/2010/12/25/algoritmo-para-detectar-colisiones-entre-rectangulos/
- https://www.genbeta.com/desarrollo/teoria-de-colisiones-2d-conceptos-basicos

**Comment by gpm0009** [comment]
Vale genial. Creo que entendido. Me pongo a ello. Muchísimas gracias!!
