### ISSUE TITLE
Detección de solapamiento

### ISSUE THREAD

**Issue by gpm0009** [gpm0009/TFG_MetrominutoWeb#93]
- Discretizar líneas.
- Investigar acerca del código para cambiar el método.

- https://www.gamedev.net/articles/programming/general-and-gameplay-programming/2d-rotated-rectangle-collision-r2604/
- https://stackoverflow.com/questions/115426/algorithm-to-detect-intersection-of-two-rectangles
- https://stackoverflow.com/questions/11670028/area-of-intersection-of-two-rotated-rectangles
- https://gamedev.stackexchange.com/questions/25397/obb-vs-obb-collision-detection
- https://www.ragestorm.net/tutorial?id=22

**Comment by gpm0009** [comment]
@alvarag , Cuando te referías a discretizar la línea, tenías en mente algo de este estilo? He estado mirando y creo que puede servir. 
[Bresenham's line algorithm](https://en.wikipedia.org/wiki/Bresenham's_line_algorithm)

**Comment by alvarag** [comment]
Sí, esa es la idea pero en vez de utilizar todos los puntos de la línea, podrías dibujar una especie de línea punteada y así evitas tanta carga de CPU. Si en una línea de tamaño 40 pixeles la transformas a 10 pixeles, seguirás pudiendo calcular solapamientos y haces muchas menos comprobaciones.

Vamos, que mi método es mucho más sencillo que el que planteas pues es solo calcular puntos que pertenecen a la línea, y esto se puede hacer con una simple fórmula.

**Comment by gpm0009** [comment]
@alvarag , si el lunes tienes un ratillo......podría preguntarte un par de dudas sobre el último commit? Que creo que tengo algo mal pero no consigo ver el que :/

**Comment by alvarag** [comment]
Sin problemas, me dices cuando te vaya bien. Prefiero por la mañana.

**Comment by gpm0009** [comment]
Perfecto, yo a partir de las 12:00 me es indiferente. Si te va mal despues de esa hora dime. Gracias

**Comment by gpm0009** [comment]
Finalmente, con la solución que propuse yo (sin discretizar la línea completa) no he conseguido averiguar donde estaba el error. Sin embargo, al intentar discretizar la línea completa, proyectando la distancia y demás que me comentasteis, he conseguido esto, que quitando el marcador de arriba (estoy en ello), queda bastante mejor:
![image.png](https://images.zenhubusercontent.com/5a001aa88a75884b90862723/20fdd6ed-821b-4dc2-9f2e-90a94cbdeec5)

**Comment by alvarag** [comment]
Queda más presentable, pero echa un ojo a los desplazamientos: los marcadores 1, 4 y 5 quedan muy pegados, mientras que 0 6 y 2 quedan bien

**Comment by gpm0009** [comment]
Para evitar solapamientos entre los labels, al calcular la posición de dicho label añadir los puntos de las esquinas del rectángulo que forma a la lista de puntos discretizados. De este modo, al comprobar el siguiente label se comprueba también que no se solape con este último.
